# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# IP: ip/dds_compiler_1/dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_0_0/system_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_0_0 || ORIG_REF_NAME==system_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_0_0/system_cfg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_0_0 || ORIG_REF_NAME==system_cfg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_0/system_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_0 || ORIG_REF_NAME==system_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_0/system_rate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_0 || ORIG_REF_NAME==system_rate_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_0/system_cic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_0 || ORIG_REF_NAME==system_cic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_conv_0_0/system_conv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv_0_0 || ORIG_REF_NAME==system_conv_0_0} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_0/system_writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_writer_0_0 || ORIG_REF_NAME==system_writer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dna_0_0/system_dna_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dna_0_0 || ORIG_REF_NAME==system_dna_0_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_1_0/system_concat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_1_0 || ORIG_REF_NAME==system_concat_1_0} -quiet] -quiet

# IP: bd/system/ip/system_sts_0_0/system_sts_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sts_0_0 || ORIG_REF_NAME==system_sts_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_axi_periph_0/system_ps_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_axi_periph_0 || ORIG_REF_NAME==system_ps_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_broadcaster_0_2/system_axis_broadcaster_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_broadcaster_0_2 || ORIG_REF_NAME==system_axis_broadcaster_0_2} -quiet] -quiet

# IP: bd/system/ip/system_ch1_mem_fb_split_0/system_ch1_mem_fb_split_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ch1_mem_fb_split_0 || ORIG_REF_NAME==system_ch1_mem_fb_split_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_1/system_cic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_1 || ORIG_REF_NAME==system_cic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_ch1_output_dac_mem_split_0/system_ch1_output_dac_mem_split_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ch1_output_dac_mem_split_0 || ORIG_REF_NAME==system_ch1_output_dac_mem_split_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_combiner_0_0/system_axis_combiner_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_combiner_0_0 || ORIG_REF_NAME==system_axis_combiner_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_7_1/system_slice_7_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_7_1 || ORIG_REF_NAME==system_slice_7_1} -quiet] -quiet

# IP: bd/system/ip/system_b_const_16b_1/system_b_const_16b_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_b_const_16b_1 || ORIG_REF_NAME==system_b_const_16b_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_1/system_slice_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_1 || ORIG_REF_NAME==system_slice_6_1} -quiet] -quiet

# IP: bd/system/ip/system_output_binary_conver_0_0/system_output_binary_conver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_output_binary_conver_0_0 || ORIG_REF_NAME==system_output_binary_conver_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_2/system_slice_6_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_2 || ORIG_REF_NAME==system_slice_6_2} -quiet] -quiet

# IP: bd/system/ip/system_feedback_combined_0_0/system_feedback_combined_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_feedback_combined_0_0 || ORIG_REF_NAME==system_feedback_combined_0_0} -quiet] -quiet

# IP: ip/dds_compiler_1/dds_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: ip/c_counter_binary_0/c_counter_binary_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_axis_broadcaster_0_2/system_axis_broadcaster_0_2_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_ch1_mem_fb_split_0/system_ch1_mem_fb_split_0_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_ch1_output_dac_mem_split_0/system_ch1_output_dac_mem_split_0_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: /home/acoustics/Documents/RP/RP_feedback/feedback.gen/sources_1/bd/system/system_ooc.xdc
