#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Aug 12 15:47:11 NZST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 axi_utils_v2_0_6 cic_compiler_v4_0_15 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_dwidth_converter_v1_1_21 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_20 xbip_dsp48_macro_v3_0_18 xlconcat_v2_1_4 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axis_broadcaster_v1_1_21 axis_combiner_v1_1_20 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_pll_0_0/system_pll_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_pll_0_0/system_pll_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_ps_0_0/sim/system_ps_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_const_0_0/sim/system_const_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_0_0/sim/system_rst_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/afda/src/axis_red_pitaya_adc.v" \
    "$ref_dir/../../../bd/system/ip/system_adc_0_0/sim/system_adc_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/f42e/src/axis_red_pitaya_dac.v" \
    "$ref_dir/../../../bd/system/ip/system_dac_0_0/sim/system_dac_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/df40/src/axi_cfg_register.v" \
    "$ref_dir/../../../bd/system/ip/system_cfg_0_0/sim/system_cfg_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/1dd6/src/port_slicer.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_0_0/sim/system_slice_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_1_0/sim/system_slice_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_2_0/sim/system_slice_2_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_3_0/sim/system_slice_3_0.v" \
    "$ref_dir/../../../bd/system/ipshared/b446/src/axis_variable.v" \
    "$ref_dir/../../../bd/system/ip/system_rate_0_0/sim/system_rate_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cic_compiler_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/0aa2/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_cic_0_0/sim/system_cic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_dwidth_converter_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/6614/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_conv_0_0/sim/system_conv_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/8cfb/src/axis_ram_writer.v" \
    "$ref_dir/../../../bd/system/ip/system_writer_0_0/sim/system_writer_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_4_0/sim/system_slice_4_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_6_0/sim/system_slice_6_0.v" \
    "$ref_dir/../../../bd/system/ipshared/457f/src/axis_constant.v" \
    "$ref_dir/../../../bd/system/ip/system_phase_0_0/sim/system_phase_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_20 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/398e/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_dds_0_0/sim/system_dds_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_macro_v3_0_18 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/f5aa/hdl/xbip_dsp48_macro_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mult_0_0/sim/system_mult_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_slice_5_0/sim/system_slice_5_0.v" \
    "$ref_dir/../../../bd/system/ip/system_slice_7_0/sim/system_slice_7_0.v" \
    "$ref_dir/../../../bd/system/ip/system_phase_1_0/sim/system_phase_1_0.v" \
    "$ref_dir/../../../bd/system/ipshared/5f76/src/dna_reader.v" \
    "$ref_dir/../../../bd/system/ip/system_dna_0_0/sim/system_dna_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_concat_1_0/sim/system_concat_1_0.v" \
    "$ref_dir/../../../bd/system/ipshared/ad5c/src/axi_sts_register.v" \
    "$ref_dir/../../../bd/system/ip/system_sts_0_0/sim/system_sts_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_0/hdl/tdata_system_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_0/hdl/tuser_system_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/30ef/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_0/hdl/top_system_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_0/sim/system_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_2/hdl/tdata_system_axis_broadcaster_0_2.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_2/hdl/tuser_system_axis_broadcaster_0_2.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_2/hdl/top_system_axis_broadcaster_0_2.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_broadcaster_0_2/sim/system_axis_broadcaster_0_2.v" \
    "$ref_dir/../../../bd/system/ip/system_phase_0_1/sim/system_phase_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_mem_fb_split_0/hdl/tdata_system_ch1_mem_fb_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_mem_fb_split_0/hdl/tuser_system_ch1_mem_fb_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_mem_fb_split_0/hdl/top_system_ch1_mem_fb_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_mem_fb_split_0/sim/system_ch1_mem_fb_split_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_cic_0_1/sim/system_cic_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_ch1_output_dac_mem_split_0/hdl/tdata_system_ch1_output_dac_mem_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_output_dac_mem_split_0/hdl/tuser_system_ch1_output_dac_mem_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_output_dac_mem_split_0/hdl/top_system_ch1_output_dac_mem_split_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ch1_output_dac_mem_split_0/sim/system_ch1_output_dac_mem_split_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_combiner_v1_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/23ef/hdl/axis_combiner_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_combiner_0_0/sim/system_axis_combiner_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_combiner_0_1/sim/system_axis_combiner_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_AXI4_multi_adder_0_1/sim/system_AXI4_multi_adder_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_phase_0_2/sim/system_phase_0_2.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
    "$ref_dir/../../../bd/system/ip/system_const_0_1/sim/system_const_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_const_1_0/sim/system_const_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../adc_test.gen/sources_1/bd/system/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/acoustics/Documents/RP/Pavel_Demin/tmp/adc_test.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
